### ISSUE TITLE
LCG generates invalid MSIL

### ISSUE THREAD

**Issue by Sharp0802** [gazok/ploio_agent#63]
LCG seems to generates invalid MSIL:

```
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'Query'.
      System.TypeInitializationException: The type initializer for 'Frouros.Shared.Extensions.IPAddressExtension' threw an exception.
       ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
         at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
         at System.Reflection.MethodInfo.CreateDelegate[T]()
         at Frouros.Shared.Reflection.Field.CreateSetter[TType,TField](FieldInfo field) in /home/docker/ploio_agent/src/Frouros.Shared/Reflection/Field.cs:line 25
         at Frouros.Shared.Extensions.IPAddressExtension..cctor() in /home/docker/ploio_agent/src/Frouros.Shared/Extensions/IPAddressExtension.cs:line 20
         --- End of inner exception stack trace ---
         at Frouros.Shared.Extensions.IPAddressExtension.ToByteString(IPAddress addr) in /home/docker/ploio_agent/src/Frouros.Shared/Extensions/IPAddressExtension.cs:line 32
         at Frouros.Host.Services.CRIService.<>c.<Query>b__2_0(IPAddress ip) in /home/docker/ploio_agent/src/Frouros.Host/Services/CRIService.cs:line 44
         at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
         at Google.Protobuf.Collections.RepeatedField`1.AddRange(IEnumerable`1 values)
         at Google.Protobuf.Collections.RepeatedField`1.Add(IEnumerable`1 values)
         at Frouros.Host.Services.CRIService.Query(PodRequest request, ServerCallContext context) in /home/docker/ploio_agent/src/Frouros.Host/Services/CRIService.cs:line 34
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, TRequest request)
      --- End of stack trace from previous location ---
         at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
```

RPC cannot be established.

**Comment by Sharp0802** [comment]
bbc064d causes:

```
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'Query'.
      System.BadImageFormatException: Field token out of range.
         at System.Net.IPAddress.set__addressOrScopeId(IPAddress)
         at Frouros.Shared.Extensions.IPAddressExtension.ToByteString(IPAddress addr) in /home/docker/ploio_agent/src/Frouros.Shared/Extensions/IPAddressExtension.cs:line 37
         at Frouros.Host.Services.CRIService.<>c.<Query>b__2_0(IPAddress ip) in /home/docker/ploio_agent/src/Frouros.Host/Services/CRIService.cs:line 44
         at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
         at Google.Protobuf.Collections.RepeatedField`1.AddRange(IEnumerable`1 values)
         at Google.Protobuf.Collections.RepeatedField`1.Add(IEnumerable`1 values)
         at Frouros.Host.Services.CRIService.Query(PodRequest request, ServerCallContext context) in /home/docker/ploio_agent/src/Frouros.Host/Services/CRIService.cs:line 34
         at Grpc.Shared.Server.UnaryServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, TRequest request)
      --- End of stack trace from previous location ---
         at Grpc.AspNetCore.Server.Internal.CallHandlers.UnaryServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
         at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
```

**Comment by Sharp0802** [comment]
ca5b46b fixed issue!

**Comment by Sharp0802** [comment]
Tested ACK
